insert into public.questionnaires (title, description, target_department_type, estimated_minutes, status)
values
  ('IT Manager Questionnaire', 'Requirement collection for IT scope, hosting, security, and system governance.', 'IT', 20, 'published'),
  ('Maintenance Manager Questionnaire', 'Requirement collection for maintenance workflow, approvals, assignments, and reports.', 'Maintenance', 20, 'published'),
  ('Maintenance Data Entry Questionnaire', 'Requirement collection for paper form usage, numbering, filing, and manual reporting.', 'Maintenance', 20, 'published'),
  ('Maintenance Supervisor Questionnaire', 'Requirement collection for technician assignment, verification, parts, completion, and field problems.', 'Maintenance', 20, 'published'),
  ('Technician Questionnaire', 'Requirement collection for technician mobile workflow, jobs, materials, photos, and site constraints.', 'Maintenance', 15, 'published'),
  ('Store Keeper Questionnaire', 'Requirement collection for parts requests, inventory, issuing, returns, and stock controls.', 'Stores', 20, 'published'),
  ('Purchase Department Questionnaire', 'Requirement collection for purchase requests, approvals, quotations, suppliers, and attachments.', 'Purchase', 15, 'published'),
  ('Finance Department Questionnaire', 'Requirement collection for cost approval, visibility, limits, reports, currency, and budgets.', 'Finance', 15, 'published'),
  ('Department Manager / Requester Questionnaire', 'Requirement collection for maintenance request process, approvals, status tracking, and reports.', 'Operations', 15, 'published'),
  ('CEO / Management Questionnaire', 'Requirement collection for executive KPIs, approvals, cost reports, downtime, and summaries.', 'Management', 15, 'published')
on conflict do nothing;

with questionnaire_topics as (
  select q.id, topic.title, topic.sort_order
  from public.questionnaires q
  join (
    values
      ('IT Manager Questionnaire', 'System scope', 1),
      ('IT Manager Questionnaire', 'Phase 1 scope', 2),
      ('IT Manager Questionnaire', 'Hosting', 3),
      ('IT Manager Questionnaire', 'Security', 4),
      ('IT Manager Questionnaire', 'Users and roles', 5),
      ('Maintenance Manager Questionnaire', 'Work order workflow', 1),
      ('Maintenance Manager Questionnaire', 'Approval flow', 2),
      ('Maintenance Manager Questionnaire', 'Emergency work', 3),
      ('Maintenance Manager Questionnaire', 'Preventive maintenance', 4),
      ('Maintenance Data Entry Questionnaire', 'Paper form usage', 1),
      ('Maintenance Data Entry Questionnaire', 'Work order numbering', 2),
      ('Maintenance Data Entry Questionnaire', 'Manual reports', 3),
      ('Maintenance Supervisor Questionnaire', 'Technician assignment', 1),
      ('Maintenance Supervisor Questionnaire', 'Parts request process', 2),
      ('Technician Questionnaire', 'Mobile updates', 1),
      ('Technician Questionnaire', 'Current paper process pain points', 2),
      ('Store Keeper Questionnaire', 'Parts request flow', 1),
      ('Store Keeper Questionnaire', 'Spare parts inventory', 2),
      ('Purchase Department Questionnaire', 'Purchase request flow', 1),
      ('Purchase Department Questionnaire', 'Approvals and quotations', 2),
      ('Finance Department Questionnaire', 'Cost approval', 1),
      ('Finance Department Questionnaire', 'Cost reports', 2),
      ('Department Manager / Requester Questionnaire', 'Maintenance request process', 1),
      ('Department Manager / Requester Questionnaire', 'Request status tracking', 2),
      ('CEO / Management Questionnaire', 'High-level dashboard', 1),
      ('CEO / Management Questionnaire', 'KPIs and approvals', 2)
  ) as topic(questionnaire_title, title, sort_order) on topic.questionnaire_title = q.title
)
insert into public.question_categories (questionnaire_id, title, sort_order)
select id, title, sort_order from questionnaire_topics;

with question_rows as (
  select * from (
    values
      ('IT Manager Questionnaire', 1, 'Is the system only for the Maintenance Department, or should it become a company-wide workflow system later?'),
      ('IT Manager Questionnaire', 2, 'What is the phase 1 scope?'),
      ('IT Manager Questionnaire', 3, 'What is the expected deadline for the first working version?'),
      ('IT Manager Questionnaire', 4, 'Where should the system be hosted?'),
      ('IT Manager Questionnaire', 5, 'Should the system be accessible outside the company network?'),
      ('IT Manager Questionnaire', 6, 'Should login use company email, employee number, or username?'),
      ('IT Manager Questionnaire', 7, 'Is two-factor authentication required?'),
      ('IT Manager Questionnaire', 8, 'Should every action be audit logged?'),
      ('IT Manager Questionnaire', 9, 'Should the system be English only or bilingual English/Arabic?'),
      ('IT Manager Questionnaire', 10, 'Does company data need to stay inside company server or inside Kuwait?'),
      ('Maintenance Manager Questionnaire', 1, 'Who can create a work order?'),
      ('Maintenance Manager Questionnaire', 2, 'Who approves a work order?'),
      ('Maintenance Manager Questionnaire', 3, 'Does every work order need approval before work starts?'),
      ('Maintenance Manager Questionnaire', 4, 'Can emergency work start without approval?'),
      ('Maintenance Manager Questionnaire', 5, 'Who assigns technicians?'),
      ('Maintenance Manager Questionnaire', 6, 'What are the maintenance sections?'),
      ('Maintenance Manager Questionnaire', 7, 'What are the work order types?'),
      ('Maintenance Manager Questionnaire', 8, 'Who closes the work order?'),
      ('Maintenance Manager Questionnaire', 9, 'Is operator signature required after completion?'),
      ('Maintenance Manager Questionnaire', 10, 'Do you need preventive maintenance reminders?'),
      ('Maintenance Data Entry Questionnaire', 1, 'How do you currently number work orders?'),
      ('Maintenance Data Entry Questionnaire', 2, 'Are work order numbers manual or automatic?'),
      ('Maintenance Data Entry Questionnaire', 3, 'Which fields are mandatory in the current work order form?'),
      ('Maintenance Data Entry Questionnaire', 4, 'Which fields are often missing?'),
      ('Maintenance Data Entry Questionnaire', 5, 'Where do completed paper forms go?'),
      ('Maintenance Data Entry Questionnaire', 6, 'Do you use Excel for tracking?'),
      ('Maintenance Data Entry Questionnaire', 7, 'Do you prepare monthly reports manually?'),
      ('Maintenance Data Entry Questionnaire', 8, 'Should old paper work orders be entered into the new system?'),
      ('Maintenance Data Entry Questionnaire', 9, 'Should the digital form look like the paper form?'),
      ('Maintenance Data Entry Questionnaire', 10, 'Do you need PDF/print after submission?'),
      ('Technician Questionnaire', 1, 'Do technicians need their own login?'),
      ('Technician Questionnaire', 2, 'Should technicians see only assigned jobs?'),
      ('Technician Questionnaire', 3, 'Should technicians update job status from mobile?'),
      ('Technician Questionnaire', 4, 'Should technicians enter start time and finish time?'),
      ('Technician Questionnaire', 5, 'Should technicians upload before/after repair photos?'),
      ('Technician Questionnaire', 6, 'Should technicians request parts from mobile?'),
      ('Technician Questionnaire', 7, 'Is internet weak in workshop/site areas?'),
      ('Technician Questionnaire', 8, 'What is difficult in the current paper process?'),
      ('Store Keeper Questionnaire', 1, 'Do you receive parts requests from maintenance?'),
      ('Store Keeper Questionnaire', 2, 'Do you issue parts only after approval?'),
      ('Store Keeper Questionnaire', 3, 'Do you have spare parts inventory now?'),
      ('Store Keeper Questionnaire', 4, 'Is inventory in Excel, ERP, or paper?'),
      ('Store Keeper Questionnaire', 5, 'What does SS rec code mean?'),
      ('Store Keeper Questionnaire', 6, 'Is part number available for all items?'),
      ('Store Keeper Questionnaire', 7, 'Can parts be partially issued?'),
      ('Store Keeper Questionnaire', 8, 'What happens if parts are not available?'),
      ('Store Keeper Questionnaire', 9, 'Should stock reduce automatically after issue?'),
      ('Store Keeper Questionnaire', 10, 'Should unused parts be returned to store?'),
      ('Purchase Department Questionnaire', 1, 'When does maintenance send purchase request?'),
      ('Purchase Department Questionnaire', 2, 'Is purchase request created by maintenance or store?'),
      ('Purchase Department Questionnaire', 3, 'Who approves purchase request?'),
      ('Purchase Department Questionnaire', 4, 'Do you need multiple quotations?'),
      ('Purchase Department Questionnaire', 5, 'Who selects supplier?'),
      ('Purchase Department Questionnaire', 6, 'Does purchase need to update request status?'),
      ('Purchase Department Questionnaire', 7, 'Should purchase status connect to the maintenance work order?'),
      ('Purchase Department Questionnaire', 8, 'Do you already have a purchase system?'),
      ('Finance Department Questionnaire', 1, 'Does finance approve maintenance cost?'),
      ('Finance Department Questionnaire', 2, 'Who can see prices?'),
      ('Finance Department Questionnaire', 3, 'Should normal maintenance users see prices?'),
      ('Finance Department Questionnaire', 4, 'Are approval limits based on amount?'),
      ('Finance Department Questionnaire', 5, 'Does CEO approve high-value repairs?'),
      ('Finance Department Questionnaire', 6, 'Should reports show cost by department, asset, vehicle, and month?'),
      ('Finance Department Questionnaire', 7, 'What currency should be used?'),
      ('Finance Department Questionnaire', 8, 'Do you need budget tracking?'),
      ('Department Manager / Requester Questionnaire', 1, 'How do you currently request maintenance?'),
      ('Department Manager / Requester Questionnaire', 2, 'Who is allowed to submit maintenance request from your department?'),
      ('Department Manager / Requester Questionnaire', 3, 'Should department manager approve before sending to maintenance?'),
      ('Department Manager / Requester Questionnaire', 4, 'Should you see status of your request?'),
      ('Department Manager / Requester Questionnaire', 5, 'Do you need notification when work is completed?'),
      ('Department Manager / Requester Questionnaire', 6, 'Should you confirm completion?'),
      ('Department Manager / Requester Questionnaire', 7, 'Should you see maintenance cost or not?'),
      ('Department Manager / Requester Questionnaire', 8, 'What reports do you need from maintenance?'),
      ('CEO / Management Questionnaire', 1, 'What KPIs should management see?'),
      ('CEO / Management Questionnaire', 2, 'Should CEO see all departments and all work orders?'),
      ('CEO / Management Questionnaire', 3, 'Should CEO approve high-cost maintenance or purchase requests?'),
      ('CEO / Management Questionnaire', 4, 'What cost limit requires CEO approval?'),
      ('CEO / Management Questionnaire', 5, 'Do you need monthly maintenance summary?'),
      ('CEO / Management Questionnaire', 6, 'Do you need asset downtime report?'),
      ('CEO / Management Questionnaire', 7, 'Do you need overdue work order report?'),
      ('CEO / Management Questionnaire', 8, 'Do you need department-wise cost comparison?')
  ) as rows(questionnaire_title, sort_order, question_text)
)
insert into public.questions (questionnaire_id, question_text, question_type, is_required, sort_order)
select q.id, qr.question_text, 'long_text', true, qr.sort_order
from question_rows qr
join public.questionnaires q on q.title = qr.questionnaire_title;
